server: 
   port: 8080
eureka: 
   server:
     enable-self-preservation: false
     eviction-interval-time-in-ms: 4000
   client: 
     registerWithEureka: false
     fetchRegistry: false
   serviceUrl: 
     defaultZone: https://www.jiujichina:8080/eureka/
