spring: 
    application: 
      name: eureka
server: 
   port: 8080
eureka: 
   server:
     enable-self-preservation: false
     eviction-interval-time-in-ms: 4000
   instance:
    hostname: www.jiujichina.com
   client: 
     registerWithEureka: false
     fetchRegistry: false
   serviceUrl: 
     defaultZone: https://www.jiujichina.com:8080/eureka/
