server: 
   port: 8761
eureka: 
   server:
     enable-self-preservation: false
     eviction-interval-time-in-ms: 4000
   client: 
     registerWithEureka: false
     fetchRegistry: false
   serviceUrl: 
     defaultZone: http://localhost:8761/eureka/
